		<!--footer-->
		<footer class="footer-distributed">

			<div class="footer-left">

				<h3>MD<span>Tutor</span></h3>

				<p class="footer-links">
				</p>

				<p class="footer-company-name">Mount Doug CS12 © 2023</p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>
					<p><span>3970 Gordon Head Rd.</span> Victoria, British Columbia</p>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>+250-477-6977</p>
				</div>

				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:cjdickson@sd61.bc.ca">cjdickson@sd61.bc.ca</a></p>
				</div>

			</div>

			<div class="footer-right">

				<p class="footer-company-about">
					<span>About Us</span>
					Mount Douglas' peer tutors are available to help you with all of your academic needs and assist with homework, test preparation and studying skills.<br>

				<div class="footer-icons">

					<a href="https://www.instagram.com/mtdougpeertutoring//"><i class="fa fa-instagram"></i></a>
					<a href="https://mountdoug.sd61.bc.ca">MD</a>

				</div>

			</div>

		</footer>
  </body>
  
</html>