 <div class ="header">
  <h1>Welcome To Peer Tutoring</h1>
  </div>


<div class="grid-handler">

  <div class="left" id="mainleft">

  


  
  </div>
<div class="leftText">
    See which tutors are available using our state of the art calendar<br><br>
  <a href="?page=calendar" class="innerLeft" style="background-color:white;">Calendar</a></li>
</div>
  <div class="middle">

  
  
  </div>
<div class="middleText">
Browse our large selection of peer and their areas of expertise<br><br>
 <a href="?page=home" style="background-color:white;">View Profiles</a></li>

</div>

  <div class="right">
  Join the tutors and help out your fellow Rams!<br><br>
  <a href="?page=form" style="background-color:white;">Join Our Team</a></li>
  
  </div>

  
  <div class="pmid">

  </div>
	<div class="pmidText">
	Search for specific tutors, courses, or grades <br><br>
  <a href="?page=search" style="background-color:white;">Search Profiles</a></li>
	</div>

  </ul>
</div>
  